#!/bin/bash

upath=`echo ${0/compileF/}`
path=`readlink -f $upath`

fortcomp=$1

if [ "$#" == "0" ]; then 
echo "Fortran90 compiler not specified"
echo "Default fortran 90 compiler: /home/sankar/bin/ifort"
fortcomp=/home/sankar/bin/ifort
fi

chs=`which $fortcomp`
echo $chs

if [[ $chs == *"$fortcomp"* ]]; then
echo "$fortcomp FOUND"
else
echo "$fortcomp NOT FOUND to be installed"
exit;
fi

rm -f $path/EXEC/*.exe

$fortcomp $path/EXEC/globuleN.f -o $path/EXEC/glbN.exe
$fortcomp $path/EXEC/metsph.f -o $path/EXEC/msph.exe
$fortcomp $path/EXEC/accall.f -o $path/EXEC/accall.exe
$fortcomp $path/EXEC/delasa.f -o $path/EXEC/delasa.exe
$fortcomp $path/EXEC/hdist.f -o $path/EXEC/hdist.exe
$fortcomp $path/EXEC/buryasa.f -o $path/EXEC/buryasa.exe
$fortcomp $path/EXEC/fetchintsurf.f -o $path/EXEC/fetchds.exe
$fortcomp $path/EXEC/corrcoefPsplw.f -o $path/EXEC/ccpsw.exe
$fortcomp $path/EXEC/metcoord.f -o $path/EXEC/mcoord.exe
$fortcomp $path/EXEC/intf2surf.f -o $path/EXEC/isurf.exe
$fortcomp $path/EXEC/dsl.f -o $path/EXEC/dsl.exe
$fortcomp $path/EXEC/Pgrid.f -o $path/EXEC/Pgr.exe
$fortcomp $path/EXEC/cmpi2intScEC.f -o $path/EXEC/cmpI.exe
$fortcomp $path/EXEC/transsquare.f -o $path/EXEC/trsq.exe
$fortcomp $path/EXEC/transdock.f -o $path/EXEC/trdn.exe


chmod +x EXEC/*.pl
chmod +x EXEC/*.bash
cp LIBR/DB3-SE.trsq .

Nfort=`ls $path/EXEC/*.f | wc -l`
Nfort=`echo ${Nfort} | bc -l` 
echo $Nfort

Nexec=`ls $path/EXEC/*.exe | wc -l`
echo $Nexec

if [ "$Nexec" == "$Nfort" ]; then
echo "Compilation Successful"
fi

